### ISSUE TITLE
Feature Request: Make preferred network used for connection requests configurable

### ISSUE THREAD

**Issue by MonitorComputing** [JMRI/EngineDriver#731] opened 2020-10-09 12:48 UTC
Recent discussions on Groups.IO for JMRI have revealed that in the more recent versions of Android when Mobile Data is available and connected WiFi has no Internet connectivity then Mobile Data is always used for new connection requests regardless of the target IP address matching the WiFi network.

It would be useful if Engine Driver could be configured to override this preference to any network other than Mobile Data. These needs to be configurable because connecting via Mobile Data is a valid scenario even if a somewhat unusual one.

**Comment by flash62au** [comment] 2020-10-09 19:11
Hi,
Awhile ago I spent over a week trying to force ED to use the WiFi rather than mobile data.
I was not successful.
There are plenty of suggestions on the web on how to address it as this seems to be a common problem, but nothing I found matches the way ED communicates.


Peter

**Comment by Alan-RMA49** [comment] 2020-10-15 18:03
Hi all,

It's great to see this is being given another shot. I've joined github just to follow this request and provide any help I can in terms of user feedback, although I'm well aware it's currently a request and nothing more. I won't be much use in terms of coding but my line of work (mobile device management software) causes me to spend a fair bit of time fiddling with Android phones / tablets / boxes to get things configured the way our customers need them configured.

I'm confident it can be done, going back to my example of Canon's "Camera Connect" app that quite happily ignores the mobile data connection in order to retrieve the photos from my camera's internet-less wifi network.

My original post on groups.io was locked after Chris raised the feature request (lots of "just turn off mobile data" replies), but here's the link in case it can provide anything useful :
https://groups.io/g/jmriusers/topic/using_engine_driver_on_a/77350081?p=,,,50,0,0,0::recentpostdate%2Fsticky,,,50,2,0,77350081

I ran a series of tests to confirm that the behaviour I was seeing was indeed Android forcing ED to use the mobile data connection rather than a bug in the app. I reproduced it with Android 7 and 9. The results are there too if you're interested (post 180977).

Alan

**Comment by mattharris** [comment] 2020-10-15 18:36
Alan,

If you look at PRs #732 #733 #734 #735 these contain the work that @flash62au has done to implement this.

Right now, this is only available if you build the code yourself.

Best regards, 

Matt H

**Comment by flash62au** [comment] 2020-10-15 21:30
Alan,
we think we have had some success with the problem.  At least it is working in our test environments.  
The change should be included in the next beta release.

Peter Akers

**Comment by Alan-RMA49** [comment] 2020-10-16 13:18
Thanks Peter,

I'm taking my first tentative steps with Android Studio... I'll be able to test it properly once I've figured out what's causing the "App not installed" error when pushing the APK to my phone (might be that it's unsigned), but so far I've run it in the emulator and can see the option. Good call having mobile data "off" by default. Sounds like it's working as expected on your end anyway but I'm looking forward to trying it out.

Alan

**Comment by flash62au** [comment] 2020-10-16 20:11
Alan,
I you have the real version of ED (from the Play Store) I don't think AS will install over the top of it. Do a backup of your preferences (bottom of the preferences page) then uninstall ED.
You should be able to install your version from AS then. Then you can restore your preferences. 

Peter Akers

**Comment by Alan-RMA49** [comment] 2020-10-16 23:53
Thanks Peter,

That'll teach me not to think things through, I assumed the apps' manifests would be different enough to allow them to sit side-by-side... After uninstalling ED I was able to install the APK and I'm now happily connecting to the layout without having to disable mobile data, excellent stuff!

Looking forward to seeing the update hit the Play Store so I can get it onto our members' phones. The amount of time I spend helping people with the wifi / mobile data every club night is unbelievable.

Got a nice little setup on the club layout as of this evening, with JMRI hooked up to a Lenz USB/Ethernet/XpressNet module (23151) allowing us to control trains using both smartphones and Multimaus controllers simultaneously, meaning everyone's happy.

Thanks for making such things possible.

Alan

**Comment by flash62au** [comment] 2020-10-17 09:53
Thanks for the feedback. Glad it worked. 
I did some testing at my club today and it was equally successful.

Peter

**Comment by mstevetodd** [comment] 2020-10-24 11:40
I have pushed a new Beta to the Play Store, 2.26.115. 
In this version, Peter made changes to force use of the wifi connection, even when no Internet connection is available. 
Thanks, Peter!

**Comment by mstevetodd** [comment] 2021-04-06 14:23
This has been in production for a while with no known issues. Closing.

**Closed by mstevetodd** 2021-04-06 14:23 UTC
