### ISSUE TITLE
Enhancement: Add support for graphical buttons (instead of text) using icons stored in decoderpro roster

### ISSUE THREAD

**Issue by DrCodeWizzard** [JMRI/EngineDriver#366] opened 2018-10-22 01:05 UTC
As an end user it would be great if EngineDriver supported use of graphical button icons set in DecoderPro Roster. It would prevent shortening of function names in the throttles. 

This request is related to the following issue:

https://github.com/JMRI/JMRI/issues/5943

As result of the earlier request I have created and uploaded an initial set of over 380 64x64 png icons that could be used for depictions of functions on sound engines. 

Here's are examples of how of how a steam engine with 11 functions is graphically represented in Z21 app, JRMI Throttle, JRMI roster. I am also attaching a copy of that roster.

![content___com google android googlequicksearchbox commoncontentprovider_assist com google android apps gsa staticplugins assist screenshot screenshotprovider_com google android apps gsa staticplugins assist screenshot scr](https://user-images.githubusercontent.com/20030645/47274525-03b64680-d574-11e8-9e42-55fd2a051554.png)
![br-38 icons and function descriptions](https://user-images.githubusercontent.com/20030645/47274529-16c91680-d574-11e8-9da9-d4a9f8c35f27.png)
![european locos in roster](https://user-images.githubusercontent.com/20030645/47274530-1761ad00-d574-11e8-8900-f4b3bc35d892.png)
![throttle](https://user-images.githubusercontent.com/20030645/47274532-192b7080-d574-11e8-9417-76b31685961c.png)
[exampleroster.zip](https://github.com/JMRI/EngineDriver/files/2499842/exampleroster.zip)

**Comment by mattharris** [comment] 2018-10-22 12:41
duplicate of #365

**Closed by mattharris** 2018-10-22 12:41 UTC
